[API]
base_url = http://127.0.0.1:8000
authenticate_endpoint = /core/api/Auth/authenticate
get_objects_id = /core/api/objects/select
get_blob_id = /core/api/files/objects/{obj_id}
download_endpoint = /core/api/files/objects/{obj_id}/files/{blob_id}
send_content = /core/api/objects/{obj_id}/attributes
username = your_username
password = your_password
polling_interval = 60

[Paths]
results_dir = ./results

[Processing]
#Расширение файлов, через запятую
extensions = .dwg.pdf
#Включает отправку текста в IPS
is_production = true
#Сохраняет изображения в папку /results
save_images = true
debug = true

[OCR]
dpi = 300
#Язык распознавания
lang = rus
#ОЕМ модификатор
psm = 6
#Хз что такое
use_advanced_recognition = true
min_area_ratio = 0.005
width_tolerance = 0.3
#---Настройки захвата облака текста---
kernel_width = 20
kernel_height = 30
#-------------------------------------
dilation_iterations = 3
char_whitelist = 
#АБВГДЕЁЖЗИЙКЛМНОПРСТУФХЦЧШЩЪЫЬЭЮЯабвгдеёжзийклмнопрстуфхцчшщъыьэюя0123456789.,:;()-+/№ 

[Selection]
# Ключевые слова для поиска технических требований (через запятую)
keywords = материал,гост,допуски,требования,пункт,размеры,технические требования,общие допуски,покрытие,маркировать,сварка,пункт,пункты

[Exclusion]
# Ключевые слова для исключения блоков (подписи, штампы и т.п.)
exclude_keywords = подписан,сертификат,эцп,укэп,унэп,владелец подписи,действительно,действителен,квалифицированной,электронной подписью